
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: localDB
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MissionApp
    depends_on:
      - mongodb
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "mongodb://mongodb:27017/localDB"
    links:
      - mongodb